// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXcsOQc6kgG3CdiIEN6IK9Ij9nr2VwnMg',
    appId: '1:325344634473:web:a01b784e989bd2b8d0e4f8',
    messagingSenderId: '325344634473',
    projectId: 'nombramientosoj',
    authDomain: 'nombramientosoj.firebaseapp.com',
    storageBucket: 'nombramientosoj.firebasestorage.app',
    measurementId: 'G-S4Z9JP4ZD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB19oR3Yjy8w54gsiXKrN9wH5vBVmh7Bes',
    appId: '1:325344634473:android:4ca81c9af5aae3fed0e4f8',
    messagingSenderId: '325344634473',
    projectId: 'nombramientosoj',
    storageBucket: 'nombramientosoj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe6USuaODpQR2oNEJARLX01hXBh9kk9r4',
    appId: '1:325344634473:ios:d31cd79e22e69822d0e4f8',
    messagingSenderId: '325344634473',
    projectId: 'nombramientosoj',
    storageBucket: 'nombramientosoj.firebasestorage.app',
    iosBundleId: 'com.example.nombramientosApp',
  );
}
